version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=bdSG
      - POSTGRES_USER=dab
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_volumes:/var/lib/postgresql
volumes:
  postgres_volumes:
    external: true